name: tf_gpu_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - statsmodels
  - tqdm
  - pillow
  - nibabel
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - tensorly
  - pip:
      - tensorflow==2.18.0
      - keras==3.6.0
      - tensorflow-hub==0.16.1
      - transformers==4.41.2
      - scikit-survival==0.23.0
      - pycox==0.2.3
      - torchtuples
